### ISSUE TITLE
Fix deprecated datetime function in `manage-voters.php`

### ISSUE THREAD

**Issue by biellamariscotes** [BSIT-3-1-APPDEV/PUPSRC-AutomatedElectionSystem#119] opened 2024-05-30 15:57 UTC
Code Block [line 373]:
```php
class=""><?php echo date("F j, Y", strtotime($row["status_updated"])); ?>
``` 
Error Logs:
```
2024-05-30 10:26 pm Error: [8192] strtotime(): Passing null to parameter #1 ($datetime) of type string is deprecated - C:\xampp\htdocs\PUPSRC-AutomatedElectionSystem\src\manage-voters.php: 373
```

**Comment by Carl-Tabuso** [comment] 2024-05-31 09:15
You do the closing on your pull request not here. Now before your pull request is even merged, the issue is already closed. LOL

**Closed as completed** 2024-05-31 15:42 UTC
Labels: released
